### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by palbha** [ColeMurray/medium-facenet-tutorial#20]
Hi is there any way i can run this without using docker as i am totally unaware of it .

**Comment by ColeMurray** [comment]
Hello @palbha,

Yes, you could install the dependencies manually if you did not want to use Docker.

Dependencies:
- Opencv3
- Dlib

The remaining dependencies can be installed through
``` pip install -r requirements.txt```

**Comment by palbha** [comment]
Other then that for running the code , I don't require to use docker or what ?

**Comment by ColeMurray** [comment]
@palbha, Docker is used to create a reproducible environment setup. It ensures that your setup will exactly mirror the tutorial.

It's not required to run the application. All dependencies can be installed manually.

**Comment by palbha** [comment]
Hi Cole , thanks i tried running the code and now facing issue while running the train classifier ..
<Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.


Please suggest , Thanks in advance

**Comment by ColeMurray** [comment]
@palbha,

The error you are seeing is due to using a different version of Tensorflow than the tutorial (this is the problem docker helps solve 😄).

Run this command 
```
python -c 'import tensorflow as tf; print(tf.__version__)'  # for Python 2
python3 -c 'import tensorflow as tf; print(tf.__version__)'  # for Python 3
```

The results you'll see will likely not be ```1.1.0```

There are two paths you can take to resolve this. You can downgrade your Tensorflow version to 1.1.0, or modify the code to use the new Tensorflow api's.

For downgrading, run ```pip install tensorflow==1.1.0 --force-reinstall```. 

For upgrading, you'll need to work through the errors thrown and continually update the code. The specific error listed above should be fixable by changing to ```tf.data.from_tensors(tensor).repeat(num_epochs)```. There will likely be other errors.

Thank you,

Cole Murray
